name: pkgcheck1

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
      - cron: '35 13 * * *' # Daily

jobs:
  pkgcheck1:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonfischl1980/gentoo-ci:main
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: emerge-sync
      run: |
        sudo -u portage git -C /var/db/repos/gentoo pull
        emerge --sync

    - name: repos.conf/HomeAssistantRepository
      run: |
        mkdir -p /etc/portage/repos.conf/
        echo -en "[HomeAssistantRepository]\nlocation = " >/etc/portage/repos.conf/HomeAssistantRepository.conf
        pwd -P >> /etc/portage/repos.conf/HomeAssistantRepository.conf
        cat /etc/portage/repos.conf/*.conf

    - name: pkgcheck scan
      run: |
        pkgcheck scan -c=-RedundantVersionCheck,-VisibilityCheck
